Update template to v0.5.0 (#100)
* Automated template update to v0.5.0

* remove 1 empty line in conf.py

---------

Co-authored-by: eroell <eljas.roellin@ikmail.com>

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -12,12 +12,14 @@ concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
+defaults:
+  run:
+    # to fail on error in multiline statements (-e), in pipes (-o pipefail), and on unset variables (-u).
+    shell: bash -euo pipefail {0}
+
 jobs:
   test:
     runs-on: ${{ matrix.os }}
-    defaults:
-      run:
-        shell: bash -e {0} # -e to fail on error
 
     strategy:
       fail-fast: false
@@ -26,9 +28,9 @@ jobs:
           - os: ubuntu-latest
             python: "3.10"
           - os: ubuntu-latest
-            python: "3.13"
+            python: "3.12"
           - os: ubuntu-latest
-            python: "3.13"
+            python: "3.12"
             pip-flags: "--pre"
             name: PRE-RELEASE DEPENDENCIES
 
@@ -40,22 +42,18 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
-      - name: Set up Python ${{ matrix.python }}
-        uses: actions/setup-python@v5
         with:
-          python-version: ${{ matrix.python }}
-      - uses: hynek/setup-cached-uv@v2
+          filter: blob:none
+          fetch-depth: 0
+      - name: Install uv
+        uses: astral-sh/setup-uv@v5
         with:
-          cache-dependency-path: pyproject.toml
-      - name: Install dependencies
-        run: uv pip install --system ${{ matrix.pip-flags }} ".[dev,test]"
-      - name: Test
+          cache-dependency-glob: pyproject.toml
+      - name: run tests using hatch
         env:
           MPLBACKEND: agg
           PLATFORM: ${{ matrix.os }}
           DISPLAY: :42
-        run: coverage run -m pytest -v --color=yes
-      - name: Report coverage
-        run: coverage report
+        run: uvx hatch test --cover --python ${{ matrix.python }}
       - name: Upload coverage
         uses: codecov/codecov-action@v4
